export const teamData = [
  {
    id: 0,
    name: 'Sandi Bitenc',
    desc: ['Chief Executive Officer'],
    img: ['./assets/sandi.svg'],
    link: ['https://www.linkedin.com/in/sandi-bitenc-40228686/'],
  },
  {
    id: 1,
    name: 'Davor Žic',
    desc: ['Chief Technology Officer'],
    img: ['./assets/davor.svg'],
    link: [
      'https://www.linkedin.com/in/davor-%C5%BEic-43889419/?originalSubdomain=si',
    ],
  },
  {
    id: 2,
    name: 'Nejc Bukovec',
    desc: ['Chief Token Relations Officer'],
    img: ['./assets/nejc.svg'],
    link: ['https://www.linkedin.com/in/nejcbukovec/?originalSubdomain=si'],
  },
  {
    id: 3,
    name: 'Rok Mihailović Krpan',
    desc: ['Head of Development'],
    img: ['./assets/rok.svg'],
    link: ['https://www.linkedin.com/in/rok-mihailovi%C4%87-krpan-2a12a114b/'],
  },
  {
    id: 4,
    name: 'Domen Leš',
    desc: ['Lead Developer'],
    img: ['./assets/domen.svg'],
    link: ['https://www.linkedin.com/in/dle%C5%A1/'],
  },
  {
    id: 5,
    name: 'Samo Zorger ',
    desc: ['Operations Associate'],
    img: ['./assets/samo.svg'],
    link: ['https://www.linkedin.com/in/samozorger/'],
  },
  {
    id: 6,
    name: 'Laura P. Sterle',
    desc: ['Lead Graphic Designer'],
    img: ['./assets/laura.svg'],
    link: ['https://www.linkedin.com/in/laura-p-sterle-7a7397211/'],
  },
  {
    id: 7,
    name: 'Ruba Aramouny',
    desc: ['Chief Marketing Officer'],
    img: ['./assets/ruba.svg'],
    link: ['https://www.linkedin.com/in/ruba-aramouny/'],
  },
  {
    id: 8,
    name: 'Anita Mlakar',
    desc: ['PR'],
    img: ['./assets/anita.svg'],
    link: ['https://www.linkedin.com/in/anita-mlakar/'],
  },
  {
    id: 9,
    name: 'Solome Daniel',
    desc: [' Ethiopia Operations Coordinator'],
    img: ['./assets/solome.svg'],
    link: ['https://www.linkedin.com/in/solome-daniel-3b9597177/'],
  },
];
