export const advisorsData = [
  {
    id: 0,
    name: 'Emmanuel Babs',
    desc: ['Binance Africa & Bundle'],
    img: ['./assets/babs.svg'],
    link: ['https://www.linkedin.com/in/emmexdee/?originalSubdomain=ng'],
  },
  {
    id: 1,
    name: 'Gideon Greaves',
    desc: ['MD at CV Labs Africa'],
    img: ['./assets/gideon.svg'],
    link: ['https://za.linkedin.com/in/gideon-greaves-97535348'],
  },
  {
    id: 2,
    name: 'Denis Bolčina',
    desc: ['Telecom advisor'],
    img: ['./assets/denis.svg'],
    link: ['https://www.linkedin.com/in/denis-bolcina-232203b5/'],
  },
  {
    id: 3,
    name: 'Markos Lemma',
    desc: ['Africa focused Strategic Advisor'],
    img: ['./assets/markus.svg'],
    link: ['https://www.linkedin.com/in/eweket/'],
  },
  {
    id: 4,
    name: 'Oliver von Wolff',
    desc: ['Strategy and Financial Advisor'],
    img: ['./assets/von.svg'],
    link: ['https://www.linkedin.com/in/oliver-von-wolff-63146639/'],
  },
  {
    id: 5,
    name: 'KEY',
    desc: ['Blockchain & Strategy Advisor'],
    img: ['./assets/key.svg'],
    link: ['https://in.linkedin.com/in/mrkey'],
  },
  {
    id: 6,
    name: 'James Bernard',
    desc: ['Blockchain Advisor'],
    img: ['./assets/james.svg'],
    link: ['https://www.linkedin.com/in/jamesdbernard/'],
  },
  {
    id: 7,
    name: 'Dustin Plantholt',
    desc: ['Plantholt Advisory Group'],
    img: ['./assets/dustin.svg'],
    link: ['https://www.linkedin.com/in/plantholt'],
  },
  {
    id: 8,
    name: 'Michał Domarecki',
    desc: ['Co-CEO Synapse Network'],
    img: ['./assets/michael.svg'],
    link: ['https://uk.linkedin.com/in/michal-domarecki'],
  },
];
